name: scanner 
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  http: ^1.1.0
  dio: ^5.4.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.jpg # <-- your launcher icon
    - assets/Frame.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
